<a href="https://colab.research.google.com/github/AlehZahorski/ml_basics/blob/main/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

In [2]:
import pandas as pd

data = {
    'size': ['XL', 'L', 'M', 'L', 'M'],
    'color': ['red', 'green', 'blue', 'green', 'red'],
    'gender': ['female', 'male', 'male', 'female', 'female'],
    'price': [199.0, 89.0, 99.0, 129.0, 79.0],
    'weight': [500, 450, 300, 380, 410],
    'bought': ['yes', 'no', 'yes', 'no', 'yes']
}

df_raw = pd.DataFrame(data=data)
df_raw

  size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [4]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      object
 1   color   5 non-null      object
 2   gender  5 non-null      object
 3   price   5 non-null      float64
 4   weight  5 non-null      int64
 5   bought  5 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes

In [7]:
for col in ['size', 'color', 'gender', 'bought']:
    df[col] = df[col].astype('category')

df['weight'] = df['weight'].astype('float')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64
 4   weight  5 non-null      float64
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes

In [10]:
df.describe(include=['category']).T

       count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [11]:
df

  size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
le.fit(df['bought'])
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [13]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [14]:
le.classes_

array(['no', 'yes'], dtype=object)

In [15]:
df['bought'] = le.fit_transform(df['bought'])
df

  size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [32]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [33]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [39]:
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoder.fit_transform(df[['size']])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [40]:
df

  size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [41]:
pd.get_dummies(data=df)

,price,weight,bought,size_L,size_M,size_XL,color_blue,color_green,color_red,gender_female,gender_male
0,199.0,500.0,1,False,False,True,False,False,True,True,False
1,89.0,450.0,0,True,False,False,False,True,False,False,True
2,99.0,300.0,1,False,True,False,True,False,False,False,True
3,129.0,380.0,0,True,False,False,False,True,False,True,False
4,79.0,410.0,1,False,True,False,False,False,True,True,False

In [42]:
pd.get_dummies(data=df, drop_first=True)

   price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1   False     True        False       True        False
1   89.0   450.0       0   False    False         True      False         True
2   99.0   300.0       1    True    False        False      False         True
3  129.0   380.0       0   False    False         True      False        False
4   79.0   410.0       1    True    False        False       True        False

In [46]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='_')

   price  weight  bought  size_M  size_XL  color_green  color_red  gender_male
0  199.0   500.0       1   False     True        False       True        False
1   89.0   450.0       0   False    False         True      False         True
2   99.0   300.0       1    True    False        False      False         True
3  129.0   380.0       0   False    False         True      False        False
4   79.0   410.0       1    True    False        False       True        False