<a href="https://colab.research.google.com/github/AlehZahorski/ml_basics/blob/main/supervised/01_basics/03_feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

sklearn.__version__

'1.6.1'

In [2]:
def fetch_financial_data(company='AMZN'):
    """
    This function fetches stock market quotations.
    """
    import pandas_datareader.data as web
    return web.DataReader(name=company, data_source='stooq')

df_raw = fetch_financial_data()
df_raw.head()

               Open      High      Low   Close    Volume
Date
2026-03-24  207.950  209.3500  206.640  207.24  35351425
2026-03-23  209.790  212.8000  209.510  210.14  44277356
2026-03-20  207.400  207.5400  204.316  205.37  63694603
2026-03-19  207.060  209.1200  206.050  208.76  36440622
2026-03-18  213.925  215.1401  208.825  209.87  37846642

In [3]:
df = df_raw.copy()
df = df[:5]
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5 entries, 2026-03-24 to 2026-03-18
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Open    5 non-null      float64
 1   High    5 non-null      float64
 2   Low     5 non-null      float64
 3   Close   5 non-null      float64
 4   Volume  5 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 240.0 bytes

In [4]:
df['day'] = df.index.day
df['month'] = df.index.month
df['year'] = df.index.year
df

               Open      High      Low   Close    Volume  day  month  year
Date
2026-03-24  207.950  209.3500  206.640  207.24  35351425   24      3  2026
2026-03-23  209.790  212.8000  209.510  210.14  44277356   23      3  2026
2026-03-20  207.400  207.5400  204.316  205.37  63694603   20      3  2026
2026-03-19  207.060  209.1200  206.050  208.76  36440622   19      3  2026
2026-03-18  213.925  215.1401  208.825  209.87  37846642   18      3  2026

In [5]:
df.index

DatetimeIndex(['2026-03-24', '2026-03-23', '2026-03-20', '2026-03-19',
               '2026-03-18'],
              dtype='datetime64[ns]', name='Date', freq=None)

In [6]:
df = pd.DataFrame(data={'height': [175., 176.5, 185.,191.,184.5,183.,168.]})
df

   height
0   175.0
1   176.5
2   185.0
3   191.0
4   184.5
5   183.0
6   168.0

In [7]:
df['height_cat'] = pd.cut(x=df.height, bins=3)
df

   height          height_cat
0   175.0  (167.977, 175.667]
1   176.5  (175.667, 183.333]
2   185.0    (183.333, 191.0]
3   191.0    (183.333, 191.0]
4   184.5    (183.333, 191.0]
5   183.0  (175.667, 183.333]
6   168.0  (167.977, 175.667]

In [10]:
pd.get_dummies(df, drop_first=True, prefix='height')

   height  height_(175.667, 183.333]  height_(183.333, 191.0]
0   175.0                      False                    False
1   176.5                       True                    False
2   185.0                      False                     True
3   191.0                      False                     True
4   184.5                      False                     True
5   183.0                       True                    False
6   168.0                      False                    False

In [11]:
df = pd.DataFrame(data={'lang': [['PL', 'ENG'], ['GER', 'ENG', 'PL', 'FRA'], ['RU']]})
df

                  lang
0            [PL, ENG]
1  [GER, ENG, PL, FRA]
2                 [RU]

In [12]:
df['lang_number'] = df['lang'].apply(len)
df

                  lang  lang_number
0            [PL, ENG]            2
1  [GER, ENG, PL, FRA]            4
2                 [RU]            1

In [13]:
df['PL_flag'] = df['lang'].apply(lambda x: 1 if 'PL' in x else 0)
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                 [RU]            1        0

In [14]:
df

                  lang  lang_number  PL_flag
0            [PL, ENG]            2        1
1  [GER, ENG, PL, FRA]            4        1
2                 [RU]            1        0

In [15]:
df_test = df_raw.copy()
df_test

               Open      High      Low    Close    Volume
Date
2026-03-24  207.950  209.3500  206.640  207.240  35351425
2026-03-23  209.790  212.8000  209.510  210.140  44277356
2026-03-20  207.400  207.5400  204.316  205.370  63694603
2026-03-19  207.060  209.1200  206.050  208.760  36440622
2026-03-18  213.925  215.1401  208.825  209.870  37846642
...             ...       ...      ...      ...       ...
2021-04-01  155.897  158.1220  155.778  158.050  58806360
2021-03-31  153.203  155.9660  153.125  154.704  61877920
2021-03-30  153.501  153.6500  151.700  152.764  46752060
2021-03-29  152.772  154.5620  151.422  153.786  54919360
2021-03-26  152.203  152.8330  149.800  152.602  66258480

[1254 rows x 5 columns]

In [28]:
from numpy._core.numeric import astype

df_test['more_than_200'] = df_test['High'].astype(float).apply(lambda x: 1 if x > 200 else 0)
df_test

               Open      High      Low    Close    Volume  more_than_200
Date
2026-03-24  207.950  209.3500  206.640  207.240  35351425              1
2026-03-23  209.790  212.8000  209.510  210.140  44277356              1
2026-03-20  207.400  207.5400  204.316  205.370  63694603              1
2026-03-19  207.060  209.1200  206.050  208.760  36440622              1
2026-03-18  213.925  215.1401  208.825  209.870  37846642              1
...             ...       ...      ...      ...       ...            ...
2021-04-01  155.897  158.1220  155.778  158.050  58806360              0
2021-03-31  153.203  155.9660  153.125  154.704  61877920              0
2021-03-30  153.501  153.6500  151.700  152.764  46752060              0
2021-03-29  152.772  154.5620  151.422  153.786  54919360              0
2021-03-26  152.203  152.8330  149.800  152.602  66258480              0

[1254 rows x 6 columns]

In [29]:
df = pd.DataFrame(data={'website': ['wp.pl', 'onet.pl', 'google.com']})
df

      website
0       wp.pl
1     onet.pl
2  google.com

In [32]:
new = df.website.str.split('.', expand=True)
df['portal'] = new[0]
df['domain'] = new[1]
df

      website  portal domain
0       wp.pl      wp     pl
1     onet.pl    onet     pl
2  google.com  google    com